Repository diskin-lab-chop/AutoGVP, pull requests merged in 2023-07, with the labels that each got.

#53 Refactor cavatica R script
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: bix-dev, ready for review

#49 intervar adjustment issue
  AutoGVP/01-annotate_variants_custom_input.R
  AutoGVP/input/issue46_autopvs1.txt
  AutoGVP/input/issue46_intervar.txt
Labels: work in progress

#57 Add columns to abridged output
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: ready for review

#59 update multianno and intervar df sorting
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: ready for review

#68 Remove gnomad, variant AF and depth filtering
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: ready for review

#69 further removed filtering info from comments, options, and functions
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: ready for review

#71 filter multianno,intervar,autopvs1 files for vcf variants
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: ready for review

#70 add issue and PR templates
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/report-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#78 Issue77
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
  AutoGVP/input/issue50_InterVar.hg38_multianno.txt.intervar
  AutoGVP/input/issue50_VEP.vcf
  AutoGVP/input/issue50_autopvs1.txt
  AutoGVP/input/issue50_multianno.txt
Labels: ready for review

#44 checks if required user input files exist and if variants match
  AutoGVP/00-file_and_variant_check.pl
Labels: ready for review

#92 deleted unnecc results dir
  AutoGVP/results/out_annotations_report.abridged.tsv
Labels: ready for review

#96 resolve discordant calls between variant_summary and submission_summary
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: ready for review

#98 Create comprehensive AutoGVP output
  AutoGVP/01-annotate_variants_CAVATICA_input.R
  AutoGVP/01-annotate_variants_custom_input.R
Labels: ready for review, stacked
